config/routes.rb
Rails.application.routes.draw do
  
  resources :representantefs do
    member do
      put "like", to: "representantefs#upvote"
    end
  end

  resources :representantens do
    member do
      put "like", to: "representantens#upvote"
    end
  end

  resources :representantets do
    member do
      put "like", to: "representantets#upvote"
    end
  end

  get 'elecciones/salir', as: :salir
  get 'elecciones/admin'

  devise_for :usuarios
  
  resources :representantems do
    member do
      put "like", to: "representantems#upvote"
    end
  end

   root to: "elecciones#inicio"

end

app/models/representantef.rb
class Representantef < ActiveRecord::Base
    acts_as_votable
    validates :nombre, presence: true
    
    has_attached_file :foto, :default_url => "/representantefs"
  	do_not_validate_attachment_file_type :foto
end

app/controllers/representantefs_controller.rb
class RepresentantefsController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_representantef, only: [:show, :edit, :update, :destroy, :upvote]

  respond_to :html

  def index
    @representantefs = Representantef.all
    respond_with(@representantefs)
  end

  def show
    respond_with(@representantef)
  end

  def new
    @representantef = Representantef.new
    respond_with(@representantef)
  end

  def edit
  end

   def create
    @representantef = Representantef.new(representantef_params)

    respond_to do |format|
      if @representantef.save
        format.html { redirect_to @representantef, notice: 'representantef was successfully created.' }
        format.json { render :show, status: :created, location: @representantef }
      else
        format.html { render :new }
        format.json { render json: @representantef.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /representantefs/1
  # PATCH/PUT /representantefs/1.json
  def update
    respond_to do |format|
      if @representantef.update(representantef_params)
        format.html { redirect_to @representantef, notice: 'representantef was successfully updated.' }
        format.json { render :show, status: :ok, location: @representantef }
      else
        format.html { render :edit }
        format.json { render json: @representantef.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /representantefs/1
  # DELETE /representantefs/1.json
  def destroy
    @representantef.destroy
    respond_to do |format|
      format.html { redirect_to representantefs_url, notice: 'representantef was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def upvote
    @representantef.upvote_by current_usuario
    redirect_to :salir
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_representantef
      @representantef = Representantef.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def representantef_params
      params.require(:representantef).permit(:nombre, :foto)
    end
end

app/helpers/representantefs_helper.rb
module RepresentantefsHelper
end

app/views/representantefs/_form.html.erb
<%= simple_form_for(@representantef, :html => { :class => 'form-horizontal' } ) do |f| %>
  <% if @representantef.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@representantef.errors.count, "error") %> prohibited this representantef from being saved:</h2>

      <ul>
      <% @representantef.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <label>Foto</label><br>
    <%= f.file_field :foto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/representantefs/_resultados.html.erb
<center>
<h1>Jornada de los fines de semana</h1>
<div class="contene">
<div class="panel panel-default">
  
  <div class="panel-body">
    <% @representantefs.each do |representantef| %>
      <div class="contene2">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><%= representantef.nombre %></h3>
          </div>
          <div class="panel-body">
            
            <%= image_tag(representantef.foto,  height: '250', width: '250') %>
            
            <div class="panel-footer">
              <span class="label label-default fa-2x boto"><%= representantef.get_upvotes.size %> Votos</span>
            </div>
            
          </div>
        </div>
      </div>
    <% end %>
      </div>
  </div>
</div>
</center>

app/views/representantefs/_votar.html.erb
<body class="homepagea">
 
<center>
    <%= image_tag("banner1.jpg", class: "banner")  %>
<br></br><br></br>
<br></br><br></br>
<h1><strong>Jornada Fines de semana</strong></h1>
<div class="contene">
<div class="panel panel-default">
  <div class="panel-heading"> <h1>Elección Representante 2015 Centro de Formación en Diseño Confección y Moda Regional Antioquia</h1></div>
  <div class="panel-body">
    <% @representantefs.each do |representantef| %>
      <div class="contene2">
        <div class="panel panel-default cambio">
          <div class="panel-heading hola">
            <h3 class="panel-title"><%= representantef.nombre %></h3>
          </div>
          <div class="panel-body">
            
            <%= image_tag(representantef.foto,  height: '250', width: '250') %>
            
            <div class="panel-footer">
            <%= link_to like_representantef_path(representantef), method: :put, class: "btn btn-default"  do %>
              
              <i class="fa fa-thumbs-o-up fa-2x"></i>
            <% end %>
            </div>
            
          </div>
        </div>
      </div>
    <% end %>
      </div>
  </div>
</div>
</center>
</body>

app/views/representantefs/edit.html.erb
<h1>Editing representantef</h1>

<%= render 'form' %>

<%= link_to 'Show', @representantef %> |
<%= link_to 'Back', representantefs_path %>

app/views/representantefs/index.html.erb
<%= current_usuario.email %>
<center>
<h1>Lista de postulados</h1>
<div class="contene">
<div class="panel panel-default">
  
  <div class="panel-body">
    <% @representantefs.each do |representantef| %>
      <div class="contene2">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title"><%= representantef.nombre %></h3>
          </div>
          <div class="panel-body">
            
            <%= image_tag(representantef.foto,  height: '250', width: '250') %>
            
            <div class="panel-footer"><%= link_to 'Editar', edit_representantef_path(representantef) %>
            <%= link_to 'Destroy', representantef, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%= link_to like_representantef_path(representantef), method: :put, class: "btn btn-default"  do %>
              <i></i>
              <%= representantef.get_upvotes.size %>
            <% end %>
            </div>
            
          </div>
        </div>
      </div>
    <% end %>
      </div>
  </div>
</div>


<br>

<%= button_to 'New representantef', new_representantef_path, class: "btn btn-info", :method => "get"%>
</center>

app/views/representantefs/new.html.erb
<h1>New representantef</h1>

<%= render 'form' %>

<%= link_to 'Back', representantefs_path %>

app/views/representantefs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @representantef.nombre %>
</p>

<%= link_to 'Edit', edit_representantef_path(@representantef) %> |
<%= link_to 'Back', representantefs_path %>