config/routes.rb
Rails.application.routes.draw do
  
  resources :representantefs do
    member do
      put "like", to: "representantefs#upvote"
    end
  end

  resources :representantens do
    member do
      put "like", to: "representantens#upvote"
    end
  end

  resources :representantets do
    member do
      put "like", to: "representantets#upvote"
    end
  end

  get 'elecciones/salir', as: :salir
  get 'elecciones/admin'

  devise_for :usuarios
  
  resources :representantems do
    member do
      put "like", to: "representantems#upvote"
    end
  end

   root to: "elecciones#inicio"

end

app/models/representanten.rb
class Representanten < ActiveRecord::Base
     acts_as_votable
    validates :nombre, presence: true
    
    has_attached_file :foto, :default_url => "/representantens"
  	do_not_validate_attachment_file_type :foto
end

app/controllers/representantens_controller.rb
class RepresentantensController < ApplicationController
   before_action :authenticate_usuario!
  before_action :set_representanten, only: [:show, :edit, :update, :destroy, :upvote]

  respond_to :html

  def index
    @home_pagebb = true
    @representantens = Representanten.all
    respond_with(@representantens)
  end

  def show
    respond_with(@representanten)
  end

  def new
    @representanten = Representanten.new
    respond_with(@representanten)
  end

  def edit
  end

 def create
    @representanten = Representanten.new(representanten_params)

    respond_to do |format|
      if @representanten.save
        format.html { redirect_to @representanten, notice: 'representanten was successfully created.' }
        format.json { render :show, status: :created, location: @representanten }
      else
        format.html { render :new }
        format.json { render json: @representanten.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /representantens/1
  # PATCH/PUT /representantens/1.json
  def update
    respond_to do |format|
      if @representanten.update(representanten_params)
        format.html { redirect_to @representanten, notice: 'representanten was successfully updated.' }
        format.json { render :show, status: :ok, location: @representanten }
      else
        format.html { render :edit }
        format.json { render json: @representanten.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /representantens/1
  # DELETE /representantens/1.json
  def destroy
    @representanten.destroy
    respond_to do |format|
      format.html { redirect_to representantens_url, notice: 'representanten was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def upvote
    @representanten.upvote_by current_usuario
    redirect_to :salir
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_representanten
      @representanten = Representanten.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def representanten_params
      params.require(:representanten).permit(:nombre, :foto)
    end
end

app/helpers/representantens_helper.rb
module RepresentantensHelper
end

app/views/representantens/_form.html.erb
<%= simple_form_for(@representanten, :html => { :class => 'form-horizontal' } ) do |f| %>
  <% if @representanten.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@representanten.errors.count, "error") %> prohibited this representanten from being saved:</h2>

      <ul>
      <% @representanten.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <label>Foto</label><br>
    <%= f.file_field :foto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/representantens/_resultados.html.erb
<center>
<h1>Jornada de la noche</h1>
<div class="contene">
<div class="panel panel-default">
  
  <div class="panel-body">
    <% @representantens.each do |representanten| %>
      <div class="contene2">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><%= representanten.nombre %></h3>
          </div>
          <div class="panel-body">
            
            <%= image_tag(representanten.foto,  height: '250', width: '250') %>
            
            <div class="panel-footer">
              <span class="label label-default fa-2x boto"><%= representanten.get_upvotes.size %> Votos</span>
            </div>
            
          </div>
        </div>
      </div>
    <% end %>
      </div>
  </div>
</div>
</center>

app/views/representantens/_votar.html.erb
<body class="homepagea">
 
<center>
    <%= image_tag("banner1.jpg", class: "banner")  %>
<br></br><br></br>
<br></br><br></br>

<h1><strong>Jornada Noche</strong></h1>
<div class="contene">
<div class="panel panel-default">
  <div class="panel-heading"> <h1>Elección Representante 2015 Centro de Formación en Diseño Confección y Moda Regional Antioquia</h1></div>
  <div class="panel-body">
    <% @representantens.each do |representanten| %>
      <div class="contene2">
        <div class="panel panel-default cambio">
          <div class="panel-heading hola">
            <h3 class="panel-title"><%= representanten.nombre %></h3>
          </div>
          <div class="panel-body">
            
            <%= image_tag(representanten.foto,  height: '250', width: '250') %>
            
            <div class="panel-footer">
            <%= link_to like_representanten_path(representanten), method: :put, class: "btn btn-default"  do %>
              
              <i class="fa fa-thumbs-o-up fa-2x"></i>
            <% end %>
            </div>
            
          </div>
        </div>
      </div>
    <% end %>
      </div>
  </div>
</div>
</center>
</body>

app/views/representantens/edit.html.erb
<h1>Editing representanten</h1>

<%= render 'form' %>

<%= link_to 'Show', @representanten %> |
<%= link_to 'Back', representantens_path %>

app/views/representantens/index.html.erb
<%= current_usuario.email %>
<center>
<h1>Lista de postulados</h1>
<div class="contene">
<div class="panel panel-default">
  
  <div class="panel-body">
    <% @representantens.each do |representanten| %>
      <div class="contene2">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title"><%= representanten.nombre %></h3>
          </div>
          <div class="panel-body">
            
            <%= image_tag(representanten.foto,  height: '250', width: '250') %>
            
            <div class="panel-footer"><%= link_to 'Editar', edit_representanten_path(representanten) %>
            <%= link_to 'Destroy', representanten, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%= link_to like_representanten_path(representanten), method: :put, class: "btn btn-default"  do %>
              <i></i>
              <%= representanten.get_upvotes.size %>
            <% end %>
            </div>
            
          </div>
        </div>
      </div>
    <% end %>
      </div>
  </div>
</div>


<br>

<%= button_to 'New representanten', new_representanten_path, class: "btn btn-info", :method => "get"%>
</center>

app/views/representantens/new.html.erb
<h1>New representanten</h1>

<%= render 'form' %>

<%= link_to 'Back', representantens_path %>

app/views/representantens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @representanten.nombre %>
</p>

<%= link_to 'Edit', edit_representanten_path(@representanten) %> |
<%= link_to 'Back', representantens_path %>