config/routes.rb
Rails.application.routes.draw do
  
  resources :representantefs do
    member do
      put "like", to: "representantefs#upvote"
    end
  end

  resources :representantens do
    member do
      put "like", to: "representantens#upvote"
    end
  end

  resources :representantets do
    member do
      put "like", to: "representantets#upvote"
    end
  end

  get 'elecciones/salir', as: :salir
  get 'elecciones/admin'

  devise_for :usuarios
  
  resources :representantems do
    member do
      put "like", to: "representantems#upvote"
    end
  end

   root to: "elecciones#inicio"

end

app/models/representantet.rb
class Representantet < ActiveRecord::Base
    acts_as_votable
    validates :nombre, presence: true
    
    has_attached_file :foto, :default_url => "/representantets"
  	do_not_validate_attachment_file_type :foto
end

app/controllers/representantets_controller.rb
class RepresentantetsController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_representantet, only: [:show, :edit, :update, :destroy, :upvote]

  respond_to :html

  def index
    @home_pagecc = true
    @representantets = Representantet.all
    respond_with(@representantets)
  end

  def show
    respond_with(@representantet)
  end

  def new
    @representantet = Representantet.new
    respond_with(@representantet)
  end

  def edit
  end

  def create
    @representantet = Representantet.new(representantet_params)

    respond_to do |format|
      if @representantet.save
        format.html { redirect_to @representantet, notice: 'representantet was successfully created.' }
        format.json { render :show, status: :created, location: @representantet }
      else
        format.html { render :new }
        format.json { render json: @representantet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /representantets/1
  # PATCH/PUT /representantets/1.json
  def update
    respond_to do |format|
      if @representantet.update(representantet_params)
        format.html { redirect_to @representantet, notice: 'representantet was successfully updated.' }
        format.json { render :show, status: :ok, location: @representantet }
      else
        format.html { render :edit }
        format.json { render json: @representantet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /representantets/1
  # DELETE /representantets/1.json
  def destroy
    @representantet.destroy
    respond_to do |format|
      format.html { redirect_to representantets_url, notice: 'representantet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def upvote
    @representantet.upvote_by current_usuario
    redirect_to :salir
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_representantet
      @representantet = Representantet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def representantet_params
      params.require(:representantet).permit(:nombre, :foto)
    end
end

app/helpers/representantets_helper.rb
module RepresentantetsHelper
end

app/views/representantets/_form.html.erb
<%= simple_form_for(@representantet, :html => { :class => 'form-horizontal' } ) do |f| %>
  <% if @representantet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@representantet.errors.count, "error") %> prohibited this representantet from being saved:</h2>

      <ul>
      <% @representantet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <label>Foto</label><br>
    <%= f.file_field :foto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/representantets/_resultados.html.erb
<center>
<h1>Jornada de la tarde</h1>
<div class="contene">
<div class="panel panel-default">
  
  <div class="panel-body">
    <% @representantets.each do |representantet| %>
      <div class="contene2">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><%= representantet.nombre %></h3>
          </div>
          <div class="panel-body">
            
            <%= image_tag(representantet.foto,  height: '250', width: '250') %>
            
            <div class="panel-footer"> 
            <span class="label label-default fa-2x boto"><%= representantet.get_upvotes.size %> Votos</span>
            </div>
            
          </div>
        </div>
      </div>
    <% end %>
      </div>
  </div>
</div>
</center>

app/views/representantets/_votar.html.erb
<body class="homepagea">
 
<center>
    <%= image_tag("banner1.jpg", class: "banner")  %>
<br></br><br></br>
<br></br><br></br>
<h1><strong>Jornada Tarde</strong></h1>
<div class="contene">
<div class="panel panel-default">
  <div class="panel-heading"> <h1>Elección Representante 2015 Centro de Formación en Diseño Confección y Moda Regional Antioquia</h1></div>
  <div class="panel-body">
    <% @representantets.each do |representantet| %>
      <div class="contene2">
        <div class="panel panel-default cambio">
          <div class="panel-heading hola">
            <h3 class="panel-title"><%= representantet.nombre %></h3>
          </div>
          <div class="panel-body">
            
            <%= image_tag(representantet.foto,  height: '250', width: '250') %>
            
            <div class="panel-footer">
            <%= link_to like_representantet_path(representantet), method: :put, class: "btn btn-default"  do %>
              
              <i class="fa fa-thumbs-o-up fa-2x"></i>
            <% end %>
            </div>
            
          </div>
        </div>
      </div>
    <% end %>
      </div>
  </div>
</div>
</center>
</body>

app/views/representantets/edit.html.erb
<h1>Editing representantet</h1>

<%= render 'form' %>

<%= link_to 'Show', @representantet %> |
<%= link_to 'Back', representantets_path %>

app/views/representantets/index.html.erb
<%= current_usuario.email %>
<center>
<h1>Lista de postulados</h1>
<div class="contene">
<div class="panel panel-default">
  
  <div class="panel-body">
    <% @representantets.each do |representantet| %>
      <div class="contene2">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title"><%= representantet.nombre %></h3>
          </div>
          <div class="panel-body">
            
            <%= image_tag(representantet.foto,  height: '250', width: '250') %>
            
            <div class="panel-footer"><%= link_to 'Editar', edit_representantet_path(representantet) %>
            <%= link_to 'Destroy', representantet, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%= link_to like_representantet_path(representantet), method: :put, class: "btn btn-default"  do %>
              <i></i>
              <%= representantet.get_upvotes.size %>
            <% end %>
            </div>
            
          </div>
        </div>
      </div>
    <% end %>
      </div>
  </div>
</div>


<br>

<%= button_to 'New representantet', new_representantet_path, class: "btn btn-info", :method => "get"%>
</center>

app/views/representantets/new.html.erb
<h1>New representantet</h1>

<%= render 'form' %>

<%= link_to 'Back', representantets_path %>

app/views/representantets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @representantet.nombre %>
</p>

<%= link_to 'Edit', edit_representantet_path(@representantet) %> |
<%= link_to 'Back', representantets_path %>