config/routes.rb
Rails.application.routes.draw do
  
  resources :representantefs do
    member do
      put "like", to: "representantefs#upvote"
    end
  end

  resources :representantens do
    member do
      put "like", to: "representantens#upvote"
    end
  end

  resources :representantets do
    member do
      put "like", to: "representantets#upvote"
    end
  end

  get 'elecciones/salir', as: :salir
  get 'elecciones/admin'

  devise_for :usuarios
  
  resources :representantems do
    member do
      put "like", to: "representantems#upvote"
    end
  end

   root to: "elecciones#inicio"

end

app/models/representantem.rb
class Representantem < ActiveRecord::Base
    acts_as_votable
    validates :nombre, presence: true
    
    has_attached_file :foto, :default_url => "/representantems"
  	do_not_validate_attachment_file_type :foto
  	
  	
end

app/controllers/representantems_controller.rb
class RepresentantemsController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_representantem, only: [:show, :edit, :update, :destroy, :upvote]
  
  # GET /representantems
  # GET /representantems.json
  def index
    @representantems = Representantem.all
  end

  # GET /representantems/1
  # GET /representantems/1.json
  def show
  end

  # GET /representantems/new
  def new
    @representantem = Representantem.new
  end

  # GET /representantems/1/edit
  def edit
  end

  # POST /representantems
  # POST /representantems.json
  def create
    @representantem = Representantem.new(representantem_params)

    respond_to do |format|
      if @representantem.save
        format.html { redirect_to @representantem, notice: 'Representantem was successfully created.' }
        format.json { render :show, status: :created, location: @representantem }
      else
        format.html { render :new }
        format.json { render json: @representantem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /representantems/1
  # PATCH/PUT /representantems/1.json
  def update
    respond_to do |format|
      if @representantem.update(representantem_params)
        format.html { redirect_to @representantem, notice: 'Representantem was successfully updated.' }
        format.json { render :show, status: :ok, location: @representantem }
      else
        format.html { render :edit }
        format.json { render json: @representantem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /representantems/1
  # DELETE /representantems/1.json
  def destroy
    @representantem.destroy
    respond_to do |format|
      format.html { redirect_to representantems_url, notice: 'Representantem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def upvote
    @representantem.upvote_by current_usuario
    redirect_to :salir
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_representantem
      @representantem = Representantem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def representantem_params
      params.require(:representantem).permit(:nombre, :foto)
    end
end

app/helpers/representantems_helper.rb
module RepresentantemsHelper
end

app/views/representantems/_form.html.erb
<%= simple_form_for(@representantem, :html => { :class => 'form-horizontal' } ) do |f| %>
  <% if @representantem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@representantem.errors.count, "error") %> prohibited this representantem from being saved:</h2>

      <ul>
      <% @representantem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <label>Foto</label><br>
    <%= f.file_field :foto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/representantems/_resultados.html.erb
<center>
<h1>Jornada de la mañana</h1>
<div class="contene">
<div class="panel panel-default">
  
  <div class="panel-body">
    <% @representantems.each do |representantem| %>
      <div class="contene2">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><%= representantem.nombre %></h3>
          </div>
          <div class="panel-body">
            
            <%= image_tag(representantem.foto,  height: '250', width: '250') %>
            
            <div class="panel-footer">
              <span class="label label-default fa-2x boto"><%= representantem.get_upvotes.size %> Votos</span>
            </div>
          </div>
        </div>
      </div>
    <% end %>
      </div>
  </div>
</div>
</center>

app/views/representantems/_votar.html.erb
<center>
  <%= image_tag("banner1.jpg", class: "banner")  %>
<br></br><br></br>
<br></br><br></br>

<h1><strong>Jornada Mañana</strong></h1>
<div class="contene">
<div class="panel panel-default">
  <div class="panel-heading"> <h1>Elección Representante 2015 Centro de Formación en Diseño Confección y Moda Regional Antioquia</h1></div>
  <div class="panel-body">
    <% @representantems.each do |representantem| %>
      <div class="contene2">
        <div class="panel panel-default cambio">
          <div class="panel-heading hola">
            <h3 class="panel-title"><%= representantem.nombre %></h3>
          </div>
          <div class="panel-body">
            
            <%= image_tag(representantem.foto,  height: '250', width: '250') %>
            
            <div class="panel-footer">
            <%= link_to like_representantem_path(representantem), method: :put, class: "btn btn-default"  do %>
              
              <i class="fa fa-thumbs-o-up fa-2x"></i>
            <% end %>
            </div>
            
          </div>
        </div>
      </div>
    <% end %>
      </div>
  </div>
</div>
</center>

app/views/representantems/edit.html.erb
<h1>Editing representantem</h1>

<%= render 'form' %>

<%= link_to 'Show', @representantem %> |
<%= link_to 'Back', representantems_path %>

app/views/representantems/index.html.erb
<%= current_usuario.email %>
<center>
<h1>Lista de postulados</h1>
<div class="contene">
<div class="panel panel-default">
  
  <div class="panel-body">
    <% @representantems.each do |representantem| %>
      <div class="contene2">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title"><%= representantem.nombre %></h3>
          </div>
          <div class="panel-body">
            
            <%= image_tag(representantem.foto,  height: '250', width: '250') %>
            
            <div class="panel-footer"><%= link_to 'Editar', edit_representantem_path(representantem) %>
            <%= link_to 'Destroy', representantem, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%= link_to like_representantem_path(representantem), method: :put, class: "btn btn-default"  do %>
              <i></i>
              <%= representantem.get_upvotes.size %>
            <% end %>
            </div>
            
          </div>
        </div>
      </div>
    <% end %>
      </div>
  </div>
</div>


<br>

<%= button_to 'New Representantem', new_representantem_path, class: "btn btn-info", :method => "get"%>
</center>

app/views/representantems/new.html.erb
<h1>New representantem</h1>

<%= render 'form' %>

<%= link_to 'Back', representantems_path %>

app/views/representantems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @representantem.nombre %>
</p>
<p>
  <strong>Nombre:</strong>
  <%= image_tag(@representantem.foto) %>
</p>

<%= link_to 'Edit', edit_representantem_path(@representantem) %> |
<%= link_to 'Back', representantems_path %>